describe('Catedraticos Page', () => {
  it('Login Successful', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/catedraticos')
  })
})
it('Catedraticos Load Page', () => {
  cy.visit('/login')
  cy.get('input[name=email]')
    .type('admin@itpsm.edu.sv')
  cy.get('input[name=password]')
    .type('password')
  cy.get('button[type=submit]')
    .click()
  cy.get('h4')
    .should('contain', 'Bienvenido')
  cy.visit('/dashboard/catedraticos')
})
it('Nuevo Catedratico', () => {
  cy.visit('/login')
  cy.get('input[name=email]')
    .type('admin@itpsm.edu.sv')
  cy.get('input[name=password]')
    .type('password')
  cy.get('button[type=submit]')
    .click()
  cy.get('h4')
    .should('contain', 'Bienvenido')
  cy.visit('/dashboard/catedraticos')
  cy.get('.bg-indigo-600')
    .click()
  cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
    .clear('O')
  cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
    .type('Oscar')
  cy.get(':nth-child(1) > :nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
    .clear()
  cy.get(':nth-child(1) > :nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
    .type('A')
  cy.get('.w-1\\/2 > :nth-child(1) > .mt-1 > .appearance-none')
    .clear()
  cy.get('.w-1\\/2 > :nth-child(1) > .mt-1 > .appearance-none')
    .type('Col P')
  cy.get(':nth-child(5) > :nth-child(1) > .mt-1 > .appearance-none')
    .clear()
  cy.get(':nth-child(5) > :nth-child(1) > .mt-1 > .appearance-none')
    .type('OSCAR2@gmail.com')
  cy.get(':nth-child(6) > :nth-child(1) > .mt-1 > .appearance-none')
    .clear()
  cy.get(':nth-child(6) > :nth-child(1) > .mt-1 > .appearance-none')
    .type('1998-12-02')
  cy.get(':nth-child(7) > div > .appearance-none')
    .clear()
  cy.get(':nth-child(7) > div > .appearance-none')
    .type('7455-7899')
  cy.get(':nth-child(8) > div > .appearance-none')
    .clear()
  cy.get(':nth-child(8) > div > .appearance-none')
    .type('6548-7548')
  cy.get('#headlessui-combobox-input-10')
    .clear()
  cy.get('#headlessui-combobox-input-10')
    .type('{enter}')
  cy.get('#headlessui-combobox-button-11 > .h-5')
    .click()
  cy.get('#headlessui-combobox-option-22 > .block')
    .click()
  cy.get('#headlessui-combobox-button-14 > .h-5')
    .click()
  cy.get('#headlessui-combobox-option-24')
    .click()
  cy.get('#headlessui-combobox-input-16')
    .clear('E')
  cy.get('#headlessui-combobox-input-16')
    .type('El Salvador')
  cy.get('#headlessui-combobox-option-28 > .block')
    .click()
  cy.get('#headlessui-combobox-input-30')
    .clear('S')
  cy.get('#headlessui-combobox-input-30')
    .type('San Salvado')
  cy.get('#headlessui-combobox-option-42 > .block')
    .click()
  cy.get('#headlessui-combobox-input-52')
    .clear('S')
  cy.get('#headlessui-combobox-input-52')
    .type('Sa')
  cy.get('#headlessui-combobox-option-58 > .block')
    .click()
  cy.get(':nth-child(2) > div > .appearance-none')
    .clear('1___-______-___-_')
  cy.get(':nth-child(2) > div > .appearance-none')
    .type('1122-345667-899-0')
  cy.get(':nth-child(3) > div > .appearance-none')
    .clear('98______-_')
  cy.get(':nth-child(3) > div > .appearance-none')
    .type('98654344-3')
  cy.get(':nth-child(4) > div > .appearance-none')
    .clear('45_______')
  cy.get(':nth-child(4) > div > .appearance-none')
    .type('455435345')
  cy.get(':nth-child(5) > div > .appearance-none')
    .clear('53__________')
  cy.get(':nth-child(5) > div > .appearance-none')
    .type('534534535335')
  cy.get('.border-transparent > span')
    .click()
})
it('Actualizar Catedratico', () => {
  cy.visit('/login')
  cy.get('input[name=email]')
    .type('admin@itpsm.edu.sv')
  cy.get('input[name=password]')
    .type('password')
  cy.get('button[type=submit]')
    .click()
  cy.get('h4')
    .should('contain', 'Bienvenido')
  cy.visit('/dashboard/catedraticos')
  cy.get('[index="2"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
    .click()
  cy.get(':nth-child(7) > div > .appearance-none')
    .clear('7777-777_')
  cy.get(':nth-child(7) > div > .appearance-none')
    .type('7777-7745')
  cy.get('#headlessui-combobox-input-13')
    .click()
  cy.get('#headlessui-combobox-button-14 > .h-5')
    .click()
  cy.get('#headlessui-combobox-option-34 > .block')
    .click()
  cy.get('#headlessui-combobox-input-10')
    .click()
  cy.get('#headlessui-combobox-button-11 > .h-5')
    .click()
  cy.get('#headlessui-combobox-option-38 > .block')
    .click()
  cy.get(':nth-child(2) > :nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
    .click()
  cy.get(':nth-child(2) > :nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
    .click()
  cy.get('.border-transparent')
    .click()
})
export {}
