describe('Ciclos de Estudios Page', () => {
  it('Login Successful', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
  })
  it('Nuevo Ciclo', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/ciclo-de-estudios')
    cy.get('.mb-12 > .inline-flex')
      .click()
    cy.get('#headlessui-combobox-button-8 > .h-5')
      .click()
    cy.get('#headlessui-combobox-option-16')
      .click()
    cy.get('.mt-1 > .appearance-none')
      .click()
    cy.get('.mt-1 > .appearance-none')
      .click()
    cy.get('.border-transparent > span')
      .click()
  })
  it('Actualizar Ciclo', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/ciclo-de-estudios')

    cy.get('[index="0"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('.bg-red-600')
      .click()
  })
  it('Agregar y Eliminar Secciones', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/ciclo-de-estudios')

    cy.get('[index="0"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('#headlessui-combobox-input-10')
      .clear('d')
    cy.get('#headlessui-combobox-input-10')
      .type('d')
    cy.get('#headlessui-combobox-option-20 > .block')
      .click()
    cy.get(':nth-child(1) > .flex-wrap > :nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('1')
    cy.get(':nth-child(1) > .flex-wrap > :nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('1')
    cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('2')
    cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('2')
    cy.get(':nth-child(5) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('2')
    cy.get(':nth-child(5) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('2')

    cy.get('#headlessui-combobox-input-14')
      .clear('B')
    cy.get('#headlessui-combobox-input-14')
      .type('B')
    cy.get('#headlessui-combobox-option-88 > .block')
      .click()
    cy.get('.self-end > .inline-flex > span')
      .click()
    cy.get(':nth-child(9) > button > .h-5')
      .click()
  })
})

export {}
