describe('Estudiantes Page', () => {
  it('Login Successful', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/estudiantes')

    cy.get('.bg-indigo-600')
      .click({ force: true })
    cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('A')
    cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('A')
    cy.get(':nth-child(1) > :nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('M')
    cy.get(':nth-child(1) > :nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('M')
    cy.get(':nth-child(1) > .w-1\\/2 > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('S')
    cy.get(':nth-child(1) > .w-1\\/2 > :nth-child(1) > .mt-1 > .appearance-none')
      .type('SS')
    cy.get('#headlessui-combobox-input-22')
      .click({ force: true })
    cy.get('#headlessui-combobox-button-23 > .h-5')
      .click({ force: true })
    cy.get('#headlessui-combobox-option-46 > .block')
      .click({ force: true })
    cy.get(':nth-child(1) > :nth-child(6) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('0001-12-05')
    cy.get(':nth-child(1) > :nth-child(6) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('1997-12-05')
    cy.get(':nth-child(1) > :nth-child(7) > div > .appearance-none')
      .clear('5___-____')
    cy.get(':nth-child(1) > :nth-child(7) > div > .appearance-none')
      .type('5858-5858')
    cy.get(':nth-child(8) > div > .appearance-none')
      .clear('8___-____')
    cy.get(':nth-child(8) > div > .appearance-none')
      .type('8585-8585')
    cy.get('#headlessui-combobox-input-25')
      .click({ force: true })
    cy.get('#headlessui-combobox-button-26 > .h-5')
      .click({ force: true })
    cy.get('#headlessui-combobox-option-50 > .block')
      .click({ force: true })
    cy.get(':nth-child(1) > :nth-child(10) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('a')
    cy.get(':nth-child(1) > :nth-child(10) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('a@a.com')
    cy.get('#headlessui-combobox-input-28')
      .click({ force: true })
    cy.get('#headlessui-combobox-button-29 > .h-5 > path')
      .click({ force: true })
    cy.get('#headlessui-combobox-option-52 > .block')
      .click({ force: true })
    cy.get('#headlessui-combobox-input-31')
      .click({ force: true })
    cy.get('#headlessui-combobox-button-32 > .h-5')
      .click({ force: true })

    cy.get('#headlessui-combobox-button-32 > .h-5')
      .click()
    cy.get('#headlessui-combobox-input-31')
      .clear('E')
    cy.get('#headlessui-combobox-input-31')
      .type('E')
    cy.get('#headlessui-combobox-option-56 > .block')
      .click()
    cy.get('#headlessui-combobox-input-58')
      .click({ force: true })
    cy.get('#headlessui-combobox-button-60 > .h-5')
      .click({ force: true })
    cy.get('#headlessui-combobox-option-66 > .block')
      .click({ force: true })
    cy.get('#headlessui-combobox-input-92')
      .click({ force: true })
    cy.get('#headlessui-combobox-button-94 > .h-5')
      .click({ force: true })
    cy.get('#headlessui-combobox-option-100 > .block')
      .click({ force: true })
    cy.get(':nth-child(2) > :nth-child(5) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('2')
    cy.get(':nth-child(2) > :nth-child(5) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('2')
    cy.get(':nth-child(8) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('P')
    cy.get(':nth-child(8) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('PP')
    cy.get(':nth-child(9) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear(':')
    cy.get(':nth-child(9) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('KK')
    cy.get(':nth-child(2) > :nth-child(10) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('1')
    cy.get(':nth-child(2) > :nth-child(10) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('2000')
    cy.get('#headlessui-combobox-button-41 > .h-5')
      .click({ force: true })
    cy.get('#headlessui-combobox-option-116')
      .click({ force: true })
    cy.get(':nth-child(4) > :nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('A')
    cy.get(':nth-child(4) > :nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('Andrea')
    cy.get(':nth-child(3) > div > .appearance-none')
      .clear()
    cy.get(':nth-child(3) > div > .appearance-none')
      .type('1235-6987')
    cy.get(':nth-child(4) > :nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('1')
    cy.get(':nth-child(4) > :nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('123456789')
    cy.get('form > :nth-child(2) > :nth-child(4)')
      .click({ force: true })
    cy.get(':nth-child(4) > :nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear()
    cy.get(':nth-child(4) > :nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('LUIS')
    cy.get('form > :nth-child(2) > :nth-child(4)')
      .click({ force: true })
    cy.get(':nth-child(5) > div > .appearance-none')
      .clear('7___-____')
    cy.get(':nth-child(5) > div > .appearance-none')
      .type('7895-6234')
    cy.get(':nth-child(4) > :nth-child(6) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('P')
    cy.get(':nth-child(4) > :nth-child(6) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('Pam')
    cy.get(':nth-child(4) > :nth-child(7) > div > .appearance-none')
      .clear('4___-____')
    cy.get(':nth-child(4) > :nth-child(7) > div > .appearance-none')
      .type('4463-2145')
    cy.get('.w-1\\/3')
      .click({ force: true })
    cy.get('#headlessui-combobox-button-134 > .h-5')
      .click({ force: true })
    cy.get('#headlessui-combobox-option-138 > .block')
      .click({ force: true })
    cy.get('.mx-2')
      .click({ force: true })
    cy.get('.justify-between > .flex > .inline-flex')
      .click({ force: true })
    cy.get('[index="0"] > .MuiTableCell-paddingNone > div > :nth-child(2) > .MuiIconButton-label > .material-icons')
      .click({ force: true })
    cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('AP')
    cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('AP')
    cy.get('.w-1\\/3 > span')
      .click({ force: true })
  })
})

export {}
