describe('Evaluations Page', () => {
  it('Login Successful', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('gulgowski.javonte@hotmail.com')
    cy.get('input[name=password]')
      .type('6BZKYGN3')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
  })

  it('Configuracion de evaluaciones', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('gulgowski.javonte@hotmail.com')
    cy.get('input[name=password]')
      .type('6BZKYGN3')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/mis-secciones')
    cy.get('[index="0"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
      .click()
    cy.get(':nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('P')
    cy.get(':nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('PARCIAL FINAL')
    cy.get(':nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear()
    cy.get(':nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('PARCIAL')
    cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear()
    cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('1998-12-12')
    cy.get(':nth-child(5) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear()
    cy.get(':nth-child(5) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('100')
    cy.get('.self-end > .inline-flex > span')
      .click()
    cy.get('.max-w-7xl > :nth-child(1)')
      .click()
  })

  it('Aprobacion de plan', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/aprobaciones')

    cy.get('[index="0"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('.border-transparent')
      .click()
    cy.get('.MuiFormControl-root')
      .click()
    cy.get('.MuiDialogContent-root')
      .click()
    cy.get('#comments')
      .clear('A')
    cy.get('#comments')
      .type('Aprobado')
    cy.get('.MuiDialogActions-root > :nth-child(1)')
      .click()
    cy.get('.max-w-7xl > .bg-white')
      .click()
  })
  it('Publicacion de evaluaciones', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('gulgowski.javonte@hotmail.com')
    cy.get('input[name=password]')
      .type('6BZKYGN3')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/mis-secciones')

    cy.get('[index="0"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('.border-transparent')
      .click()
    cy.get('.max-w-7xl > .bg-white')
      .click()
  })
  it('Rechazo de plan', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/aprobaciones')

    cy.get('[index="0"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('.border-transparent')
      .click()
    cy.get('.MuiDialogContent-root')
      .click()
    cy.get('#comments')
      .clear('tes')
    cy.get('#comments')
      .type('test')
    cy.get('.MuiDialogActions-root > :nth-child(2)')
      .click()
    cy.get('.max-w-7xl > .bg-white')
      .click()
  })
})

export {}
