describe('Estudiantes Page', () => {
  it('Login Successful', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
  })

  it('Carga, actualizacion y publicacion', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('gulgowski.javonte@hotmail.com')
    cy.get('input[name=password]')
      .type('6BZKYGN3')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/evaluaciones')

    cy.get('[index="0"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('[aria-describedby="mui-48695"] > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('.MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input')
      .clear('8')
    cy.get('.MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input')
      .type('8')
    cy.get(':nth-child(2) > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('nextjs-portal')
      .click()
    cy.get(':nth-child(2) > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('[data="[object Object]"]')
      .click()
    cy.get('.MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input')
      .clear()
    cy.get('.MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input')
      .type('9')
    cy.get('[aria-describedby="mui-2736"] > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('.border-transparent')
      .click()
    cy.get('.max-w-7xl > .bg-white')
      .click()
  })
})

export {}
