describe('Estudiantes Page', () => {
  it('Login Successful', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
  })
  cy.visit('/dashboard/plan-de-estudio')

  cy.get('.mb-12 > .inline-flex')
    .click()
  cy.get(':nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
    .clear('P')
  cy.get(':nth-child(2) > :nth-child(1) > .mt-1 > .appearance-none')
    .type('PLAN 2024')
  cy.get('#headlessui-combobox-button-5 > .h-5')
    .click()
  cy.get('#headlessui-combobox-option-12 > .block')
    .click()
  cy.get('.border-transparent > span')
    .click()
  cy.get('[index="0"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
    .click()
  cy.get('#headlessui-combobox-button-24')
    .click()
  cy.get('#headlessui-combobox-option-30 > .block')
    .click()
  cy.get(':nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
    .clear('4')
  cy.get(':nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
    .type('4')
  cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
    .clear('1')
  cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
    .type('1')
  cy.get(':nth-child(5) > .inline-flex > span')
    .click()
  cy.get('#headlessui-combobox-button-24 > .h-5')
    .click()
  cy.get('#headlessui-combobox-option-124 > .block')
    .click()
  cy.get(':nth-child(1) > .flex-wrap')
    .click()
  cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
    .clear()
  cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
    .type('2')
  cy.get(':nth-child(5) > .inline-flex > span')
    .click()
  cy.get('.flex > .border-transparent > span')
    .click()
})

export {}
