describe('Users Page', () => {
  it('Login Successful', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
  })
  it('Users Page Load', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('dashboard/usuarios')
  })
  it('Users Table Load', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('dashboard/usuarios')
    cy.contains('prueba2')
  })
  it('Users Form Load', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('dashboard/usuarios')
    cy.contains('Nuevo Administrador')
      .click()
  })
  it('Users Form Use', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('dashboard/usuarios')
    cy.contains('Nuevo Administrador')
      .click()
    cy.get('input[name=name]')
      .type('probando')
    cy.get('input[name=email]')
      .type('proband2o@probando.com')
    cy.get('input[name=password]')
      .type('12345678')
    cy.contains('Guardar Usuario')
      .click()
  })
  it('Users Form Update', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('dashboard/usuarios')
    cy.contains('span[class="material-icons MuiIcon-root"]', 'edit')
      .click()
    cy.get('input[name=email]')
      .type('proband2o@probando.com')
    cy.get('input[name=password]')
      .type('12345678')
    cy.contains('Actualizar Usuario')
      .click()
  })
})

export {}
