describe('Users Page', () => {
  it('user admin create', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/usuarios')
    cy.get('.mb-12 > .inline-flex')
      .click()
    cy.get('.w-2\\/4 > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('tes')
    cy.get('.w-2\\/4 > :nth-child(1) > .mt-1 > .appearance-none')
      .type('test')
    cy.get(':nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear()
    cy.get(':nth-child(3) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('test@prueba.com')
    cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear()
    cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('12345')
    cy.get('.border-transparent > span')
      .click()
  })
  it('user admin update', () => {
    cy.visit('/login')
    cy.get('input[name=email]')
      .type('admin@itpsm.edu.sv')
    cy.get('input[name=password]')
      .type('password')
    cy.get('button[type=submit]')
      .click()
    cy.get('h4')
      .should('contain', 'Bienvenido')
    cy.visit('/dashboard/usuarios')
    cy.get('[index="0"] > .MuiTableCell-paddingNone > div > .MuiButtonBase-root > .MuiIconButton-label > .material-icons')
      .click()
    cy.get('.w-2\\/4 > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('test2')
    cy.get('.w-2\\/4 > :nth-child(1) > .mt-1 > .appearance-none')
      .type('test2')
    cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .clear('a')
    cy.get(':nth-child(4) > :nth-child(1) > .mt-1 > .appearance-none')
      .type('abcde')
    cy.get('.border-transparent > span')
      .click()
  })
})

export {}
